name: "Security Static Analysis"

on:
  pull_request: {}
  workflow_dispatch: {}
  schedule:
  - cron: '13 23 4 * *'
jobs:
  scan:
    uses: scout24/s24-sast-action/.github/workflows/security-analysis.yml@v3

    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
      GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}

